# Generated by Django 5.1 on 2024-08-19 18:34

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=255, verbose_name='Nom du site')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='Email de contact')),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('postal_address', models.TextField(blank=True, null=True, verbose_name='Adresse postale')),
                ('paypal_link', models.URLField(blank=True, null=True, verbose_name='Lien PayPal')),
                ('facebook_link', models.URLField(blank=True, null=True, verbose_name='Lien Facebook')),
                ('twitter_link', models.URLField(blank=True, null=True, verbose_name='Lien Twitter')),
                ('linkedin_link', models.URLField(blank=True, null=True, verbose_name='Lien LinkedIn')),
                ('instagram_link', models.URLField(blank=True, null=True, verbose_name='Lien Instagram')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('content', ckeditor.fields.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tags', models.ManyToManyField(blank=True, to='main.tag')),
            ],
        ),
    ]
