# Generated by Django 5.1 on 2024-08-19 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='Image de fond'),
        ),
    ]
