# Generated by Django 5.1 on 2024-08-20 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='credit',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
