# Generated by Django 5.1 on 2024-08-20 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_blogpost_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
