# Generated by Django 5.1 on 2024-08-20 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skill_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='poste',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Poste occupé'),
        ),
    ]
