# Generated by Django 5.1 on 2024-08-20 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinformation',
            name='lien_youtube',
            field=models.URLField(blank=True, null=True, verbose_name='Lien Youtube'),
        ),
    ]
